### ISSUE TITLE
Feature: Implement Captcha - Success

### ISSUE THREAD

**Issue by acheong08** [acheong08/OpenAIAuth#1]
```py
            if soup.find('img', alt='captcha'):
                print(f"{Fore.RED}[OpenAI][5] {Fore.RED}Captcha detected")

                svg_captcha = soup.find('img', alt='captcha')['src'].split(',')[1]
                decoded_svg = base64.decodebytes(svg_captcha.encode("ascii"))

                # Convert decoded svg to png
                drawing = svg2rlg(BytesIO(decoded_svg))

                # Better quality
                renderPM.drawToFile(drawing, "captcha.png", fmt="PNG", dpi=300)
                print(f"{Fore.GREEN}[OpenAI][5] {Fore.WHITE}Captcha saved to {Fore.GREEN}captcha.png"
                      + f" {Fore.WHITE}in the current directory")

                # Wait.
                captcha_input = input(f"{Fore.GREEN}[OpenAI][5] {Fore.WHITE}Please solve the captcha and "
                                      f"press enter to continue: ")
                if captcha_input:
                    print(f"{Fore.GREEN}[OpenAI][5] {Fore.WHITE}Continuing...")
                    self._part_six(state=state, captcha=captcha_input)
                else:
                    raise Exceptions.PyChatGPTException("[OpenAI][5] You didn't enter anything.")

            else:
                print(f"{Fore.GREEN}[OpenAI][5] {Fore.GREEN}No captcha detected")
                self._part_six(state=state, captcha=None)
```
Translate this to use requests and regex

**Comment by acheong08** [comment]
@alexandreteles I have added the feature you requested. You can now pass an object into the Chatbot class which contains a `solve_captcha` function. This will run if not null with raw_svg being a param input

**Comment by alexandreteles** [comment]
I'll look into the implementation when I have some free time later today. Raw svg is fine, if the captcha solver needs something different [wand-py](http://docs.wand-py.org/) will do the conversion magic.

Do you plan on adding support for this on the async version as well?

**Comment by acheong08** [comment]
> Do you plan on adding support for this on the async version as well?

The async version is maintained by @Harry-Jing so it'll take some time to implement there

**Comment by alexandreteles** [comment]
> > If I can say so, letting developers deal with storing the state information is probably the best way. As developers are currently required to save the conversation thread themselves so they can make sure the AI remembers context in future evocations, storing the auth information should be trivial.
> 
> I'm a but confused about this part. Could you explain?

When [/src/asyncChatGPT/asyncChatGPT.py:351](https://github.com/acheong08/ChatGPT/blob/37e1afd39915fd99c5e6ad1dc61776d01a56fac1/src/asyncChatGPT/asyncChatGPT.py#L351) calls the [begin](https://github.com/acheong08/OpenAIAuth/blob/24886c94597d6535402c7eba9d3bef95de95ba76/src/OpenAIAuth/OpenAIAuth.py#L56) method from `OpenAIAuth.py` it receives back a `session_token` that is then internally stored in the object and can be refreshed, if required, by calling the [refresh_session](https://github.com/acheong08/ChatGPT/blob/37e1afd39915fd99c5e6ad1dc61776d01a56fac1/src/asyncChatGPT/asyncChatGPT.py#L250) method.

This means that developers can access the token and store it for posterior use by just accessing the attribute and storing it however they prefer. What I was trying to suggest here although I did a terrible job at it (it was like 5 in the morning, I beg your pardon) is the following:

1. Add a way to provide a session token to the `Chatbot`
2. Check if the session token is still valid
3. If it's not, renew it
4. If renewing failed, run the authentication pipeline again

This should allow developers to keep session information between runs, lowering the login attempts necessary during development and deployment.

At this moment I think this is more about `ChatGPT` than `OpenAIAuth` but I'm posting my answer here to preserve the context. Please let me know if I wasn't clear enough once again, English isn't my first language so I can be a bit unclear sometimes 😄

**Comment by acheong08** [comment]
> Add a way to provide a session token to the Chatbot
Check if the session token is still valid
If it's not, renew it
If renewing failed, run the authentication pipeline again

This was done in the revChatGPT package

**Comment by alexandreteles** [comment]
> > Add a way to provide a session token to the Chatbot
> > Check if the session token is still valid
> > If it's not, renew it
> > If renewing failed, run the authentication pipeline again
> 
> This was done in the revChatGPT package

Would you mind sharing which attributes contain the relevant information at runtime?

**Comment by acheong08** [comment]
`Chatbot.config` contains all relevant authentication details. (session token, access token, email, password) while `Chatbot.conversation_id_prev_queue` contains a list of previous conversation ids and `Chatbot.parent_id_prev_queue` contains the list for previous message ids
