### ISSUE TITLE
__part_eight response 404

### ISSUE THREAD

**Issue by FAIpang** [acheong08/OpenAIAuth#10]
![8B3C9387-1285-4511-B696-931AE07C5BBB](https://user-images.githubusercontent.com/73394302/218955845-04afaa06-5f32-4e7e-b699-db4db9f2cc84.png)

I tried running the program, but the response returns 404 when this method is requested,

**Comment by xzh12** [comment]
me too

**Comment by acheong08** [comment]
Can't replicate. You guys will need to help me with some debugging

**Comment by QylinFly** [comment]
我也是同样的问题，全局梯子都不行。

**Comment by acheong08** [comment]
Use VPN maybe (Not clash and not proxy)

**Comment by QylinFly** [comment]
很多人反馈第八步，就是因为404了，返回的页面确实也是404的内容

**Comment by QylinFly** [comment]
如果代理没有起作用，应该到不了第八步

**Comment by FAIpang** [comment]
I call revChatGPT.V1. Chatbot(), login with email and password, but debugging to _part_eight found that the response is 404, which causes the session_token not to be obtained, resulting in the get_access_token not being able to get the access_token.
I tried to copy the session_token on the ChatGPT webpage and set it to the get_aceess_token method, but it still didn't work, the return result was still empty, and then I changed to the official website url to get the access_token, and the result returned 403

**Comment by xzh12** [comment]
就是代理问题。404 返回的信息表示的是不支持的国家

**Comment by acheong08** [comment]
Based on the fact that everyone here is from China, I assume it is due to a geo block by OpenAI. Please try with a VPN or proxy

**Comment by FAIpang** [comment]
> 就是代理问题。404 返回的信息表示的是不支持的国家

我用了国外代理，直接访问ChatGPT官网没有问题，可以正常使用，但通过程序访问到__part_eight返回一个404 not found的html页面

**Comment by FAIpang** [comment]
> Based on the fact that everyone here is from China, I assume it is due to a geo block by OpenAI. Please try with a VPN or proxy

I think so too, but I call login always failed and I call login with VPN, but __part_eight always response 404

**Comment by xzh12** [comment]
> > 就是代理问题。404 返回的信息表示的是不支持的国家
> 
> 我用了国外代理，直接访问ChatGPT官网没有问题，可以正常使用，但通过程序访问到__part_eight返回一个404 not found的html页面

我之前也这样的。。全局代理，命令行里也设置的还是404 ，后面只在代码里用的proxy,结果就可以了。

**Comment by FAIpang** [comment]
> > > 就是代理问题。404 返回的信息表示的是不支持的国家
> > 
> > 
> > 我用了国外代理，直接访问ChatGPT官网没有问题，可以正常使用，但通过程序访问到__part_eight返回一个404 not found的html页面
> 
> 我之前也这样的。。全局代理，命令行里也设置的还是404 ，后面只在代码里用的proxy,结果就可以了。

是直接把全局代理的地址加到代码里面吗？

**Comment by xzh12** [comment]
> > > > 就是代理问题。404 返回的信息表示的是不支持的国家
> > > 
> > > 
> > > 我用了国外代理，直接访问ChatGPT官网没有问题，可以正常使用，但通过程序访问到__part_eight返回一个404 not found的html页面
> > 
> > 
> > 我之前也这样的。。全局代理，命令行里也设置的还是404 ，后面只在代码里用的proxy,结果就可以了。
> 
> 是直接把全局代理的地址加到代码里面吗？

v2ray 选好服务器

    proxy = "http://127.0.0.1:1087"
    auth = OpenAIAuth(email_address=email, password=password, proxy=proxy,debug=True)

**Comment by FAIpang** [comment]
> > > > > 就是代理问题。404 返回的信息表示的是不支持的国家
> > > > 
> > > > 
> > > > 我用了国外代理，直接访问ChatGPT官网没有问题，可以正常使用，但通过程序访问到__part_eight返回一个404 not found的html页面
> > > 
> > > 
> > > 我之前也这样的。。全局代理，命令行里也设置的还是404 ，后面只在代码里用的proxy,结果就可以了。
> > 
> > 
> > 是直接把全局代理的地址加到代码里面吗？
> 
> v2ray 选好服务器
> 
> ```
> proxy = "http://127.0.0.1:1087"
> auth = OpenAIAuth(email_address=email, password=password, proxy=proxy,debug=True)
> ```
按照你这样设置，我这边第一步都访问不了，应该还有其他配置吧，我用代理是可以访问官网

**Comment by xinghe-gao** [comment]
the step for repeat the situation is as flowing, all actions are on the cloud server directly:

### 1.login to cloud server
ip comes from US
login server with ssh

### 2.vi /root/anaconda3/envs/chatgpt/lib/python3.9/site-packages/OpenAIAuth/OpenAIAuth.py
# 28
debug: bool = True,
$ 334 335
print(response.status_code)
exit()

### 3.python3 -m revChatGPT.V1
Type '!help' to show a full list of commands
Press enter twice to submit your question.

Logging in...
Debugger enabled on OpenAIAuth
Beginning auth process
Beginning part two
Beginning part three
Payload: callbackUrl=%2F&csrfToken=763a449998db9344b3280e218d58e3d7138c311572e95c4bb19ce57ffc382ce7&json=true
Payload length: 100
Beginning part four
Beginning part five
Beginning part six
Beginning part seven
Request went through
Response code is 302
New state found
Beginning part eight
404

**Comment by xinghe-gao** [comment]
> > > > > 就是代理问题。404 返回的信息表示的是不支持的国家
> > > > 
> > > > 
> > > > 我用了国外代理，直接访问ChatGPT官网没有问题，可以正常使用，但通过程序访问到__part_eight返回一个404 not found的html页面
> > > 
> > > 
> > > 我之前也这样的。。全局代理，命令行里也设置的还是404 ，后面只在代码里用的proxy,结果就可以了。
> > 
> > 
> > 是直接把全局代理的地址加到代码里面吗？
> 
> v2ray 选好服务器
> 
> ```
> proxy = "http://127.0.0.1:1087"
> auth = OpenAIAuth(email_address=email, password=password, proxy=proxy,debug=True)
> ```

已测试无效，直接云服务器操作也不行

**Comment by xinghe-gao** [comment]
上述问题我已经解决了，注意两点：
1.直接把应用放云服务器上跑
2.云服务器必须使用美国的
