### ISSUE TITLE
KeyError: 'accessToken'

### ISSUE THREAD

**Issue by AlaskaYoung** [acheong08/OpenAIAuth#14]
Keep getting error on seventh step, because requests are not contains "__Secure-next-auth.session-token" cookies and returns redirect location "https://explorer.api.openai.com/api/auth/error?error=AccessDenied"
tried different proxies and VPN's, none of them worked
maybe need update something?

**Comment by acheong08** [comment]
It's working for me. I need some more debug

**Comment by AlaskaYoung** [comment]
> It's working for me. I need some more debug

I noticed that this error appears only on accounts without phone number verified 
By any chance could i get authorization token before confirming phone number? 
It’s simple to register account using your repository by only replacing “login” by “register”, but anyways i still didn’t understand how to claim auth token because it is needed for confirming number by requests

**Comment by AlaskaYoung** [comment]
I noticed that i have no any access (can't even login) to explorer.api without phone number verified (but mail is verified)
So it is not possible to signup using api (?)

**Comment by acheong08** [comment]
Oh yes, you can't log in without a verified phone number

**Comment by AlaskaYoung** [comment]
But can i signup and get access token with this api?

> Oh yes, you can't log in without a verified phone number
