### ISSUE TITLE
How to use？

### ISSUE THREAD

**Issue by huluohu** [acheong08/OpenAIAuth#15]
hi

I want to know how to use this library，can you tell me？

thanks.

**Comment by suiyuex** [comment]
Here

```python
from OpenAIAuth import Authenticator


if __name__ == '__main__':
  auth = Authenticator(email_address="email@qq.com", password="password", proxy="http://host:port")
  auth.begin()
  print(auth.get_access_token())
```

**Comment by huluohu** [comment]
> Here
> 
> ```python
> from OpenAIAuth import Authenticator
> 
> 
> if __name__ == '__main__':
>   auth = Authenticator(email_address="email@qq.com", password="password", proxy="http://host:port")
>   auth.begin()
>   print(auth.get_access_token())
> ```

ok， thank you.

**Comment by huluohu** [comment]
> > Here
> > ```python
> > from OpenAIAuth import Authenticator
> > 
> > 
> > if __name__ == '__main__':
> >   auth = Authenticator(email_address="email@qq.com", password="password", proxy="http://host:port")
> >   auth.begin()
> >   print(auth.get_access_token())
> > ```
> 
> ok， thank you.

it's work .
