### ISSUE TITLE
Max retries exceeded with url: /api/auth/csrf

### ISSUE THREAD

**Issue by friday-james** [acheong08/OpenAIAuth#20]
Tried to host a proxy according to this script: https://github.com/acheong08/ChatGPT/issues/776#issuecomment-1433934405
And run it in local

```bash
uvicorn proxy:app --reload
```

Then connect to the local proxy via the awesome project revChatGPT.V2 as below
```python
from revChatGPT.V2 import Chatbot

chatbot = Chatbot(
    email=email,
    password=password,
    paid=True,
    proxy='http://0.0.0.0',
)
```

But got an error in OpenAIAuth
`
requests.exceptions.ProxyError: HTTPSConnectionPool(host='explorer.api.openai.com', port=443): Max retries exceeded with url: /api/auth/csrf (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe3a98e61d0>: Failed to establish a new connection: [Errno 111] Connection refused')))
`

How to fix this sir 🤝

**Comment by Jxells** [comment]
我也是遇到了同样的问题

**Comment by imyzx2023** [comment]
requests.exceptions.SSLError: HTTPSConnectionPool(host='explorer.api.openai.com', port=443): Max retries exceeded with url: /api/auth/csrf (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1125)')))
Question happened in 2023.03.30！！

**Comment by acheong08** [comment]
![image](https://user-images.githubusercontent.com/36258159/228714193-e0da3501-549b-4ee5-9e0f-b11f41951456.png)

**Comment by acheong08** [comment]
yup. down. will fix later

**Comment by dktobeno1** [comment]
> requests.exceptions.SSLError: HTTPSConnectionPool(host='explorer.api.openai.com', port=443): Max retries exceeded with url: /api/auth/csrf (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1125)'))) Question happened in 2023.03.30！！

same problem!the host update security protection?

**Comment by acheong08** [comment]
They deleted the back end
