### ISSUE TITLE
sslv3 alert handshake failure!!! "explorer.api.openai.com" upgrade the protection level？

### ISSUE THREAD

**Issue by dktobeno1** [acheong08/OpenAIAuth#22]
HTTPSConnectionPool(host='explorer.api.openai.com', port=443): Max retries exceeded with url: /api/auth/csrf (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1108)')))

**Comment by bincooo** [comment]
me too!
