### ISSUE TITLE
Puid

### ISSUE THREAD

**Issue by zooways** [acheong08/OpenAIAuth#29]
This project is only suitable for plus users.

**Comment by acheong08** [comment]
The Go version now works for free users without PUID. The python version is broken beyond repair

**Comment by zooways** [comment]
ok,thanks

**Comment by zooways** [comment]
I ran an error,
logs:
Location: __part_five
Status code: 400
Embedded error: error: Check details
Body is html code

MY env is :
OPENAI_EMAIL=<username>;OPENAI_PASSWORD=<password>;PROXY=http://127.0.0.1:7890

**Comment by acheong08** [comment]
OpenAI has suspended login on certain IP ranges. Try another proxy perhaps

**Comment by zooways** [comment]
ok , I'll try again. Thanks so much

**Comment by zooways** [comment]
when call partFive function , http responseCode is 400 . 
Maybe it's not the proxy that has a problem.

**Comment by acheong08** [comment]
![image](https://user-images.githubusercontent.com/36258159/232694819-f8002d3e-fa78-4cfb-b582-316da9c13da0.png)

works for me
