### ISSUE TITLE
Is it already irrelevant?

### ISSUE THREAD

**Issue by KirillPirinen** [acheong08/OpenAIAuth#32]
it has started to return the same error -> 

Error: File not found.
Location: part_one
Status code: 404
Embedded error: error: Check details

**Comment by eternalfusion** [comment]
It's broken for now, you need to get access token manually with this url: http://chat.openai.com/api/auth/session
See [https://github.com/pengzhile/pandora/commit/58dd9c5a293e2f55c4b521d0703fdeb14761d562](this commit) from reverse proxy developer. It's used to bypass first step of auth.

**Comment by acheong08** [comment]
WIP

**Comment by acheong08** [comment]
I was able to get nearly everything working until the final step. Either need a proxy for the auth callback or abuse another endpoint for it. currently a bit stuck though

**Comment by acheong08** [comment]
Works now
