### ISSUE TITLE
Is there a way to obtain an access token for the domain https://platform.openai.com/?

### ISSUE THREAD

**Issue by imlee2021** [acheong08/OpenAIAuth#35]
Is there a way to obtain an access token for the domain https://platform.openai.com/?
If an account that hasn't passed SMS verification logs in to the domain [chat.openai.com](http://chat.openai.com/), it is not possible to obtain a token from https://chat.openai.com/api/auth/session.

**Comment by acheong08** [comment]
API keys use a different system which I haven't reversed yet

**Comment by acheong08** [comment]
Not possible for me. Cloudflare protected platform.openai.com login and I don't have the incentive to get past that
