### ISSUE TITLE
I'm waiting for a version written in another programming language 

### ISSUE THREAD

**Issue by khaiphan9x** [acheong08/OpenAIAuth#36]
Easier to understand than plain cURL command line

**Comment by acheong08** [comment]
Python is here

**Comment by khaiphan9x** [comment]
> Python is here

 have you made it public yet?

**Comment by acheong08** [comment]
Look at this repo. It's right there.

**Comment by acheong08** [comment]
oops forgot to document

**Comment by acheong08** [comment]
https://github.com/acheong08/OpenAIAuth/wiki/OpenAIAuth
