### ISSUE TITLE
chat without save coversation history

### ISSUE THREAD

**Issue by khaiphan9x** [acheong08/OpenAIAuth#39]
In iOS version I see it has chat function without saving chat history, can you guide me 
![86362161-3806-41C9-B138-90BD6967061F](https://github.com/acheong08/OpenAIAuth/assets/25249169/29665c63-1283-4ad4-b7a3-9b36707a1455)
![2D73E45F-8E88-4527-86C0-C1EA89F2842D](https://github.com/acheong08/OpenAIAuth/assets/25249169/11fa35b3-fb0a-4303-b178-756138ee24b8)

**Comment by acheong08** [comment]
Wrong repo to be opening this issue
