### ISSUE TITLE
好像用不了，报没有Auth0

### ISSUE THREAD

**Issue by Lopins** [acheong08/OpenAIAuth#40]

**Comment by acheong08** [comment]
![image](https://github.com/acheong08/OpenAIAuth/assets/36258159/67429710-bad2-475c-933c-9bb240570f38)

**Comment by Lopins** [comment]
Python版本

**Comment by acheong08** [comment]
![image](https://github.com/acheong08/OpenAIAuth/assets/36258159/ecac1099-6f47-434b-bbb0-dd524d00f215)

**Comment by Lopins** [comment]
![image](https://github.com/acheong08/OpenAIAuth/assets/44494732/107ae6f1-9196-4f38-98c4-b650e25637f5)
