### ISSUE TITLE
Missing one url

### ISSUE THREAD

**Issue by gulihua10010** [acheong08/OpenAIAuth#9]
Should there be a /api/auth/callback/auth0 before the request /api/auth/session? code=%s&state=%s, otherwise it cannot be obtained

在请求/api/auth/session之前，应该还有一个/api/auth/callback/auth0?code=%s&state=%s，否则获取不到
<img width="424" alt="image" src="https://user-images.githubusercontent.com/38686919/218826379-5805f642-f912-4de5-947c-c90b8a249cc9.png">

**Comment by acheong08** [comment]
Works for me without it. Feel free to open a pull request if this doesn't work for you
